import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import styles from './page.module.css';

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <Header />
      
      <main className={styles.main}>
        <div className={styles.container}>
          <h1>Terms of Service</h1>
          <p className={styles.lastUpdated}>Last updated: November 2024</p>

          <section className={styles.section}>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Shotsy, you agree to be bound by these Terms of Service 
              and all applicable laws and regulations. If you do not agree with any of these terms, 
              you are prohibited from using this service.
            </p>
          </section>

          <section className={styles.section}>
            <h2>2. Description of Service</h2>
            <p>
              Shotsy is a SaaS platform that helps app developers create professional 
              App Store and Google Play screenshots using AI-powered caption generation.
            </p>
          </section>

          <section className={styles.section}>
            <h2>3. User Accounts</h2>
            <p>
              To use certain features of our service, you must create an account. You are 
              responsible for maintaining the confidentiality of your account and password. 
              You agree to accept responsibility for all activities that occur under your account.
            </p>
          </section>

          <section className={styles.section}>
            <h2>4. Subscription and Payments</h2>
            <ul>
              <li>Pro subscriptions are billed monthly at $5.99/month</li>
              <li>Payments are processed securely through Polar</li>
              <li>You can cancel your subscription at any time</li>
              <li>Refunds are available within 7 days of purchase</li>
              <li>Upon cancellation, access continues until the end of the billing period</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the service for any unlawful purpose</li>
              <li>Upload content that infringes on intellectual property rights</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use automated systems to access the service without permission</li>
              <li>Resell or redistribute the service without authorization</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>6. Intellectual Property</h2>
            <p>
              You retain all rights to the screenshots you upload. The captions and designs 
              generated by our AI are yours to use for any purpose. Shotsy retains all 
              rights to the platform, technology, and branding.
            </p>
          </section>

          <section className={styles.section}>
            <h2>7. Limitation of Liability</h2>
            <p>
              Shotsy is provided "as is" without warranties of any kind. We shall not be 
              liable for any indirect, incidental, special, or consequential damages resulting 
              from your use of the service.
            </p>
          </section>

          <section className={styles.section}>
            <h2>8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users 
              of any material changes via email or through the service.
            </p>
          </section>

          <section className={styles.section}>
            <h2>9. Contact</h2>
            <p>
              For questions about these Terms of Service, please contact:
              <br />
              <a href="mailto:ifytech77@gmail.com">ifytech77@gmail.com</a>
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}

